# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2214690f87aebc16669b1e96e98fdce3d96d3106ecb29df0e7e1a3ffe88cce5042410a71ed72e4752f4d3f5047a3b9a7dc07480e90a8ad0b2d68c642f711931c

test:
  secret_key_base: 92a433a1414e10e294f8a8d2f1e001370a5a8ccc00da4cea4171869aecfe8f6953e56af66f0d3eaad98f967679b5991d09275edff1aeb2b5bff13f1455f47de6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
